---
# Service
apiVersion: v1
kind: Service
metadata:
    name: asklepiosdemo-billing-service
    namespace: asklepios-sandbox
spec:
    type: ClusterIP
    selector:
        app: asklepiosdemo-billing
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: asklepiosdemo-billing
    namespace: asklepios-sandbox
spec:
    selector:
        matchLabels:
            app: asklepiosdemo-billing
    replicas: 1
    template:
        metadata:
            labels:
                app: asklepiosdemo-billing
        spec:
            containers:
                - name: asklepiosdemo-billing
                  image: registry.digitalocean.com/asklepios/asklepios-billing:r2
                  env:
                    - name: spring.profiles.active
                      value: stage,api-docs
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
                        name: asklepios-bil

            imagePullSecrets:
                - name: asklepios

